import type { AssessmentQuestion } from './types'

// ── Shared option sets ──
const LIKERT_5 = [
  { value: 1, label: 'Strongly disagree' },
  { value: 2, label: 'Disagree' },
  { value: 3, label: 'Neutral' },
  { value: 4, label: 'Agree' },
  { value: 5, label: 'Strongly agree' },
]

const FREQUENCY_5 = [
  { value: 1, label: 'Never' },
  { value: 2, label: 'Rarely' },
  { value: 3, label: 'Sometimes' },
  { value: 4, label: 'Often' },
  { value: 5, label: 'Always' },
]

const ACCURACY_5 = [
  { value: 1, label: 'Not at all like me' },
  { value: 2, label: 'A little like me' },
  { value: 3, label: 'Somewhat like me' },
  { value: 4, label: 'Very much like me' },
  { value: 5, label: 'Exactly like me' },
]

// ════════════════════════════════════════════
// MODULE 1: Who You Are — VQ (14) + GQ (10) = 24
// ════════════════════════════════════════════
const MODULE_1: AssessmentQuestion[] = [
  // ── VQ: Values Quotient ──
  { id: 'm1_vq_01', module: 1, quotient: 'VQ', dimension: 'power_achievement', format: 'likert',
    text: 'Professional success and career advancement are among my highest priorities in life.',
    options: LIKERT_5 },
  { id: 'm1_vq_02', module: 1, quotient: 'VQ', dimension: 'power_achievement', format: 'likert',
    text: 'I feel most fulfilled when I am recognized for my accomplishments.',
    options: LIKERT_5 },
  { id: 'm1_vq_03', module: 1, quotient: 'VQ', dimension: 'security_tradition', format: 'likert',
    text: 'Stability and predictability in life are more important to me than excitement and novelty.',
    options: LIKERT_5 },
  { id: 'm1_vq_04', module: 1, quotient: 'VQ', dimension: 'security_tradition', format: 'likert',
    text: 'Honoring family traditions and cultural roots is deeply important to me.',
    options: LIKERT_5 },
  { id: 'm1_vq_05', module: 1, quotient: 'VQ', dimension: 'security_tradition', format: 'likert',
    text: 'I prefer a partner who values loyalty and commitment above all else.',
    options: LIKERT_5 },
  { id: 'm1_vq_06', module: 1, quotient: 'VQ', dimension: 'benevolence_universalism', format: 'likert',
    text: 'Making a positive impact on other people\'s lives is a core part of who I am.',
    options: LIKERT_5 },
  { id: 'm1_vq_07', module: 1, quotient: 'VQ', dimension: 'benevolence_universalism', format: 'likert',
    text: 'Social justice and fairness issues genuinely affect how I see the world.',
    options: LIKERT_5 },
  { id: 'm1_vq_08', module: 1, quotient: 'VQ', dimension: 'benevolence_universalism', format: 'likert',
    text: 'I would sacrifice personal comfort to help someone in genuine need.',
    options: LIKERT_5 },
  { id: 'm1_vq_09', module: 1, quotient: 'VQ', dimension: 'stimulation_hedonism', format: 'likert',
    text: 'I actively seek out new experiences, even if they involve uncertainty.',
    options: LIKERT_5 },
  { id: 'm1_vq_10', module: 1, quotient: 'VQ', dimension: 'stimulation_hedonism', format: 'likert',
    text: 'Enjoying life in the moment is just as important as planning for the future.',
    options: LIKERT_5 },
  { id: 'm1_vq_11', module: 1, quotient: 'VQ', dimension: 'stimulation_hedonism', format: 'likert',
    text: 'A relationship without spontaneity and fun would feel suffocating to me.',
    options: LIKERT_5 },
  { id: 'm1_vq_12', module: 1, quotient: 'VQ', dimension: 'self_direction', format: 'likert',
    text: 'Having the freedom to make my own choices is non-negotiable in a relationship.',
    options: LIKERT_5 },
  { id: 'm1_vq_13', module: 1, quotient: 'VQ', dimension: 'self_direction', format: 'likert',
    text: 'I value creative expression and independent thinking over conformity.',
    options: LIKERT_5 },
  { id: 'm1_vq_14', module: 1, quotient: 'VQ', dimension: 'self_direction', format: 'likert',
    text: 'I need a partner who respects my autonomy, even when they disagree with my choices.',
    options: LIKERT_5 },

  // ── GQ: Growth Quotient ──
  { id: 'm1_gq_01', module: 1, quotient: 'GQ', dimension: 'mindset', format: 'likert',
    text: 'When I face a significant setback, I genuinely believe I can learn and improve from it.',
    options: LIKERT_5 },
  { id: 'm1_gq_02', module: 1, quotient: 'GQ', dimension: 'mindset', format: 'likert',
    text: 'I see criticism as useful information, not a personal attack.',
    options: LIKERT_5 },
  { id: 'm1_gq_03', module: 1, quotient: 'GQ', dimension: 'ambition', format: 'likert',
    text: 'I have clear goals I am actively working toward right now.',
    options: LIKERT_5 },
  { id: 'm1_gq_04', module: 1, quotient: 'GQ', dimension: 'ambition', format: 'likert',
    text: 'I am more ambitious today than I was two years ago.',
    options: LIKERT_5 },
  { id: 'm1_gq_05', module: 1, quotient: 'GQ', dimension: 'life_stage', format: 'scenario',
    text: 'Which best describes your current life focus?',
    options: [
      { value: 1, label: 'Figuring out what I want' },
      { value: 2, label: 'Building my career or education' },
      { value: 3, label: 'Establishing stability and roots' },
      { value: 4, label: 'Growing deeper in what I\'ve built' },
      { value: 5, label: 'Reinventing or pivoting to something new' },
    ] },
  { id: 'm1_gq_06', module: 1, quotient: 'GQ', dimension: 'adaptability', format: 'likert',
    text: 'When my plans fall apart, I adjust quickly rather than dwelling on what went wrong.',
    options: LIKERT_5 },
  { id: 'm1_gq_07', module: 1, quotient: 'GQ', dimension: 'adaptability', format: 'likert',
    text: 'I am comfortable with uncertainty about the future.',
    options: LIKERT_5 },
  { id: 'm1_gq_08', module: 1, quotient: 'GQ', dimension: 'shared_vision', format: 'likert',
    text: 'It is important that my partner and I share a similar vision for where we\'ll be in 5 years.',
    options: LIKERT_5 },
  { id: 'm1_gq_09', module: 1, quotient: 'GQ', dimension: 'shared_vision', format: 'likert',
    text: 'I would rather grow together with someone than settle into comfortable routines.',
    options: LIKERT_5 },
  { id: 'm1_gq_10', module: 1, quotient: 'GQ', dimension: 'mindset', format: 'likert',
    text: 'People can fundamentally change their personality if they genuinely commit to it.',
    options: LIKERT_5 },
]

// ════════════════════════════════════════════
// MODULE 2: How You Love — AQ (12) + LQ (10) = 22
// ════════════════════════════════════════════
const MODULE_2: AssessmentQuestion[] = [
  // ── AQ: Attachment Quotient ──
  { id: 'm2_aq_01', module: 2, quotient: 'AQ', dimension: 'secure', format: 'likert',
    text: 'I find it easy to get close to others and am comfortable depending on them.',
    options: LIKERT_5 },
  { id: 'm2_aq_02', module: 2, quotient: 'AQ', dimension: 'secure', format: 'likert',
    text: 'I feel confident that people I love will be there for me when I need them.',
    options: LIKERT_5 },
  { id: 'm2_aq_03', module: 2, quotient: 'AQ', dimension: 'anxious', format: 'likert',
    text: 'I often worry that my partner doesn\'t really love me or might leave.',
    options: LIKERT_5, reverseScored: true },
  { id: 'm2_aq_04', module: 2, quotient: 'AQ', dimension: 'anxious', format: 'likert',
    text: 'When my partner doesn\'t respond quickly, I tend to assume the worst.',
    options: LIKERT_5, reverseScored: true },
  { id: 'm2_aq_05', module: 2, quotient: 'AQ', dimension: 'anxious', format: 'likert',
    text: 'I need more reassurance than most people that I am valued in a relationship.',
    options: LIKERT_5, reverseScored: true },
  { id: 'm2_aq_06', module: 2, quotient: 'AQ', dimension: 'avoidant', format: 'likert',
    text: 'I feel uncomfortable when someone gets too emotionally close to me.',
    options: LIKERT_5, reverseScored: true },
  { id: 'm2_aq_07', module: 2, quotient: 'AQ', dimension: 'avoidant', format: 'likert',
    text: 'I value my independence so much that closeness can feel suffocating.',
    options: LIKERT_5, reverseScored: true },
  { id: 'm2_aq_08', module: 2, quotient: 'AQ', dimension: 'avoidant', format: 'likert',
    text: 'I tend to shut down emotionally when a partner expresses strong needs.',
    options: LIKERT_5, reverseScored: true },
  { id: 'm2_aq_09', module: 2, quotient: 'AQ', dimension: 'disorganized', format: 'likert',
    text: 'In my closest relationships, I sometimes feel both a strong desire for closeness and an urge to run away.',
    options: LIKERT_5, reverseScored: true },
  { id: 'm2_aq_10', module: 2, quotient: 'AQ', dimension: 'disorganized', format: 'likert',
    text: 'My reactions in relationships sometimes surprise even me — I can shift from warmth to withdrawal quickly.',
    options: LIKERT_5, reverseScored: true },
  { id: 'm2_aq_11', module: 2, quotient: 'AQ', dimension: 'earned_secure', format: 'likert',
    text: 'I\'ve done significant personal work (therapy, coaching, reflection) to understand my relationship patterns.',
    options: LIKERT_5 },
  { id: 'm2_aq_12', module: 2, quotient: 'AQ', dimension: 'earned_secure', format: 'likert',
    text: 'Even though my early life was difficult, I\'ve developed the ability to trust and be vulnerable.',
    options: LIKERT_5 },

  // ── LQ: Love Language Quotient (Bidirectional) ──
  { id: 'm2_lq_01', module: 2, quotient: 'LQ', dimension: 'words', format: 'likert', subtype: 'give',
    text: 'I naturally express love through verbal compliments, encouragement, and affirmation.',
    options: ACCURACY_5 },
  { id: 'm2_lq_02', module: 2, quotient: 'LQ', dimension: 'words', format: 'likert', subtype: 'receive',
    text: 'I feel most loved when my partner tells me specifically what they appreciate about me.',
    options: ACCURACY_5 },
  { id: 'm2_lq_03', module: 2, quotient: 'LQ', dimension: 'acts', format: 'likert', subtype: 'give',
    text: 'I show love by doing practical things for my partner — cooking, fixing, helping.',
    options: ACCURACY_5 },
  { id: 'm2_lq_04', module: 2, quotient: 'LQ', dimension: 'acts', format: 'likert', subtype: 'receive',
    text: 'When my partner goes out of their way to help me with something, I feel deeply cared for.',
    options: ACCURACY_5 },
  { id: 'm2_lq_05', module: 2, quotient: 'LQ', dimension: 'gifts', format: 'likert', subtype: 'give',
    text: 'I love surprising my partner with thoughtful gifts, even small ones.',
    options: ACCURACY_5 },
  { id: 'm2_lq_06', module: 2, quotient: 'LQ', dimension: 'gifts', format: 'likert', subtype: 'receive',
    text: 'Receiving a meaningful gift from my partner makes me feel truly seen and valued.',
    options: ACCURACY_5 },
  { id: 'm2_lq_07', module: 2, quotient: 'LQ', dimension: 'time', format: 'likert', subtype: 'give',
    text: 'I prioritize giving my partner my full, undivided attention when we\'re together.',
    options: ACCURACY_5 },
  { id: 'm2_lq_08', module: 2, quotient: 'LQ', dimension: 'time', format: 'likert', subtype: 'receive',
    text: 'Nothing makes me feel more loved than quality, uninterrupted time with my partner.',
    options: ACCURACY_5 },
  { id: 'm2_lq_09', module: 2, quotient: 'LQ', dimension: 'touch', format: 'likert', subtype: 'give',
    text: 'I naturally express affection through physical touch — hugs, holding hands, closeness.',
    options: ACCURACY_5 },
  { id: 'm2_lq_10', module: 2, quotient: 'LQ', dimension: 'touch', format: 'likert', subtype: 'receive',
    text: 'Physical affection from my partner is essential for me to feel connected and loved.',
    options: ACCURACY_5 },
]

// ════════════════════════════════════════════
// MODULE 3: How You Feel — EQ (14) + NQ (12) = 26
// ════════════════════════════════════════════
const MODULE_3: AssessmentQuestion[] = [
  // ── EQ: Emotional Intelligence Quotient ──
  { id: 'm3_eq_01', module: 3, quotient: 'EQ', dimension: 'self_awareness', format: 'likert',
    text: 'I can usually name exactly what I\'m feeling in a given moment.',
    options: LIKERT_5 },
  { id: 'm3_eq_02', module: 3, quotient: 'EQ', dimension: 'self_awareness', format: 'likert',
    text: 'I notice how my emotions influence my decisions, even when others don\'t see it.',
    options: LIKERT_5 },
  { id: 'm3_eq_03', module: 3, quotient: 'EQ', dimension: 'self_awareness', format: 'frequency',
    text: 'I check in with myself about how I\'m really doing emotionally.',
    options: FREQUENCY_5 },
  { id: 'm3_eq_04', module: 3, quotient: 'EQ', dimension: 'self_regulation', format: 'likert',
    text: 'When I feel a strong negative emotion, I can manage it without lashing out.',
    options: LIKERT_5 },
  { id: 'm3_eq_05', module: 3, quotient: 'EQ', dimension: 'self_regulation', format: 'likert',
    text: 'I rarely say things in anger that I later regret.',
    options: LIKERT_5 },
  { id: 'm3_eq_06', module: 3, quotient: 'EQ', dimension: 'self_regulation', format: 'likert',
    text: 'I can sit with uncomfortable emotions without needing to fix or escape them immediately.',
    options: LIKERT_5 },
  { id: 'm3_eq_07', module: 3, quotient: 'EQ', dimension: 'empathy', format: 'likert',
    text: 'I can usually tell how someone is feeling, even when they haven\'t said anything.',
    options: LIKERT_5 },
  { id: 'm3_eq_08', module: 3, quotient: 'EQ', dimension: 'empathy', format: 'likert',
    text: 'When someone shares something painful, I feel it with them rather than just hearing it.',
    options: LIKERT_5 },
  { id: 'm3_eq_09', module: 3, quotient: 'EQ', dimension: 'empathy', format: 'likert',
    text: 'I adjust how I communicate based on what the other person seems to need in the moment.',
    options: LIKERT_5 },
  { id: 'm3_eq_10', module: 3, quotient: 'EQ', dimension: 'social_mastery', format: 'likert',
    text: 'I can navigate tense social situations without making them worse.',
    options: LIKERT_5 },
  { id: 'm3_eq_11', module: 3, quotient: 'EQ', dimension: 'social_mastery', format: 'likert',
    text: 'People often come to me when they need help resolving a conflict.',
    options: LIKERT_5 },
  { id: 'm3_eq_12', module: 3, quotient: 'EQ', dimension: 'motivation', format: 'likert',
    text: 'I am driven by internal purpose rather than external rewards like money or status.',
    options: LIKERT_5 },
  { id: 'm3_eq_13', module: 3, quotient: 'EQ', dimension: 'motivation', format: 'likert',
    text: 'I persist through challenges because the work itself matters to me.',
    options: LIKERT_5 },
  { id: 'm3_eq_14', module: 3, quotient: 'EQ', dimension: 'motivation', format: 'likert',
    text: 'I set meaningful goals that align with my personal values, not just societal expectations.',
    options: LIKERT_5 },

  // ── NQ: Neurobiological Quotient ──
  { id: 'm3_nq_01', module: 3, quotient: 'NQ', dimension: 'vagal_tone', format: 'likert',
    text: 'I can generally calm myself down within a few minutes of feeling stressed or overwhelmed.',
    options: LIKERT_5 },
  { id: 'm3_nq_02', module: 3, quotient: 'NQ', dimension: 'vagal_tone', format: 'likert',
    text: 'My body relaxes easily — I don\'t carry chronic tension in my shoulders, jaw, or chest.',
    options: LIKERT_5 },
  { id: 'm3_nq_03', module: 3, quotient: 'NQ', dimension: 'stress_response', format: 'scenario',
    text: 'When someone I care about raises their voice at me, my most honest first reaction is:',
    options: [
      { value: 5, label: 'I stay present and try to understand what\'s happening' },
      { value: 4, label: 'I feel tense but can manage myself' },
      { value: 3, label: 'I go quiet and pull inward (freeze)' },
      { value: 2, label: 'I match their energy and get defensive (fight)' },
      { value: 1, label: 'I need to physically leave the room (flight)' },
    ] },
  { id: 'm3_nq_04', module: 3, quotient: 'NQ', dimension: 'stress_response', format: 'scenario',
    text: 'Under extreme stress, I tend to:',
    options: [
      { value: 5, label: 'Stay regulated and problem-solve' },
      { value: 4, label: 'Feel anxious but function normally' },
      { value: 3, label: 'Shut down emotionally until it passes' },
      { value: 2, label: 'Become irritable and reactive' },
      { value: 1, label: 'Try to please everyone to reduce the tension' },
    ] },
  { id: 'm3_nq_05', module: 3, quotient: 'NQ', dimension: 'co_regulation', format: 'likert',
    text: 'I can help calm a partner down when they\'re upset, just by being present with them.',
    options: LIKERT_5 },
  { id: 'm3_nq_06', module: 3, quotient: 'NQ', dimension: 'co_regulation', format: 'likert',
    text: 'My presence tends to make people around me feel safer and more at ease.',
    options: LIKERT_5 },
  { id: 'm3_nq_07', module: 3, quotient: 'NQ', dimension: 'co_regulation', format: 'likert',
    text: 'I instinctively know when to give space versus when to move closer during a partner\'s distress.',
    options: LIKERT_5 },
  { id: 'm3_nq_08', module: 3, quotient: 'NQ', dimension: 'arousal_threshold', format: 'likert',
    text: 'I prefer calm, quiet environments over loud, high-energy ones.',
    options: LIKERT_5 },
  { id: 'm3_nq_09', module: 3, quotient: 'NQ', dimension: 'arousal_threshold', format: 'likert',
    text: 'Sensory overload (noise, crowds, bright lights) drains me faster than most people.',
    options: LIKERT_5 },
  { id: 'm3_nq_10', module: 3, quotient: 'NQ', dimension: 'recovery_speed', format: 'likert',
    text: 'After an argument, I can return to feeling connected within hours rather than days.',
    options: LIKERT_5 },
  { id: 'm3_nq_11', module: 3, quotient: 'NQ', dimension: 'recovery_speed', format: 'likert',
    text: 'I don\'t hold grudges — once something is resolved, I genuinely let it go.',
    options: LIKERT_5 },
  { id: 'm3_nq_12', module: 3, quotient: 'NQ', dimension: 'recovery_speed', format: 'likert',
    text: 'Stressful events from weeks ago can still affect my mood and energy today.',
    options: LIKERT_5, reverseScored: true },
]

// ════════════════════════════════════════════
// MODULE 4: How You Communicate — CQ (12) + CSQ (8) = 20
// ════════════════════════════════════════════
const MODULE_4: AssessmentQuestion[] = [
  // ── CQ: Conflict Quotient ──
  { id: 'm4_cq_01', module: 4, quotient: 'CQ', dimension: 'competing', format: 'likert',
    text: 'In a disagreement, it\'s important to me that my point wins.',
    options: ACCURACY_5 },
  { id: 'm4_cq_02', module: 4, quotient: 'CQ', dimension: 'competing', format: 'likert',
    text: 'I would rather be right than keep the peace.',
    options: ACCURACY_5 },
  { id: 'm4_cq_03', module: 4, quotient: 'CQ', dimension: 'collaborating', format: 'likert',
    text: 'When we disagree, I look for a solution that fully addresses both of our concerns.',
    options: ACCURACY_5 },
  { id: 'm4_cq_04', module: 4, quotient: 'CQ', dimension: 'collaborating', format: 'likert',
    text: 'I believe most relationship conflicts have a win-win solution if you look hard enough.',
    options: ACCURACY_5 },
  { id: 'm4_cq_05', module: 4, quotient: 'CQ', dimension: 'compromising', format: 'likert',
    text: 'I\'m willing to meet in the middle, even if neither of us gets exactly what we want.',
    options: ACCURACY_5 },
  { id: 'm4_cq_06', module: 4, quotient: 'CQ', dimension: 'compromising', format: 'likert',
    text: 'Finding a quick, fair compromise matters more to me than finding the perfect solution.',
    options: ACCURACY_5 },
  { id: 'm4_cq_07', module: 4, quotient: 'CQ', dimension: 'avoiding', format: 'likert',
    text: 'I tend to avoid bringing up issues that might start a conflict.',
    options: ACCURACY_5 },
  { id: 'm4_cq_08', module: 4, quotient: 'CQ', dimension: 'avoiding', format: 'likert',
    text: 'I sometimes let problems build up rather than address them directly.',
    options: ACCURACY_5 },
  { id: 'm4_cq_09', module: 4, quotient: 'CQ', dimension: 'accommodating', format: 'likert',
    text: 'I often give in to my partner\'s wishes to avoid tension.',
    options: ACCURACY_5 },
  { id: 'm4_cq_10', module: 4, quotient: 'CQ', dimension: 'accommodating', format: 'likert',
    text: 'Keeping my partner happy matters more to me than getting my own way.',
    options: ACCURACY_5 },
  { id: 'm4_cq_11', module: 4, quotient: 'CQ', dimension: 'gottman_risk', format: 'frequency',
    text: 'During arguments, I find myself criticizing my partner\'s character rather than addressing the specific issue.',
    options: FREQUENCY_5, reverseScored: true },
  { id: 'm4_cq_12', module: 4, quotient: 'CQ', dimension: 'gottman_risk', format: 'frequency',
    text: 'When feeling attacked, I shut down completely and stop responding.',
    options: FREQUENCY_5, reverseScored: true },

  // ── CSQ: Cognitive Style Quotient ──
  { id: 'm4_csq_01', module: 4, quotient: 'CSQ', dimension: 'analytical_intuitive', format: 'scenario',
    text: 'When making an important decision, I tend to:',
    options: [
      { value: 1, label: 'Analyze all data and options systematically' },
      { value: 2, label: 'Lean on data but trust my gut for the final call' },
      { value: 3, label: 'Balance logic and intuition equally' },
      { value: 4, label: 'Follow my instincts, then verify with logic' },
      { value: 5, label: 'Trust my gut feeling above all else' },
    ] },
  { id: 'm4_csq_02', module: 4, quotient: 'CSQ', dimension: 'analytical_intuitive', format: 'likert',
    text: 'I need to understand the reasoning behind a decision before I can accept it.',
    options: LIKERT_5 },
  { id: 'm4_csq_03', module: 4, quotient: 'CSQ', dimension: 'verbal_linguistic', format: 'likert',
    text: 'I express myself best through words — writing or speaking.',
    options: LIKERT_5 },
  { id: 'm4_csq_04', module: 4, quotient: 'CSQ', dimension: 'verbal_linguistic', format: 'likert',
    text: 'I think through problems by talking about them out loud.',
    options: LIKERT_5 },
  { id: 'm4_csq_05', module: 4, quotient: 'CSQ', dimension: 'abstract_concrete', format: 'likert',
    text: 'I prefer discussing ideas and possibilities over practical details.',
    options: LIKERT_5 },
  { id: 'm4_csq_06', module: 4, quotient: 'CSQ', dimension: 'interpersonal_intrapersonal', format: 'scenario',
    text: 'When processing something difficult, I prefer to:',
    options: [
      { value: 1, label: 'Work through it alone first, then share conclusions' },
      { value: 2, label: 'Mostly process alone, occasionally check in' },
      { value: 3, label: 'A mix of alone time and talking it through' },
      { value: 4, label: 'Mostly talk it through, but need some alone time too' },
      { value: 5, label: 'Think out loud with someone I trust' },
    ] },
  { id: 'm4_csq_07', module: 4, quotient: 'CSQ', dimension: 'creative_systematic', format: 'likert',
    text: 'I\'m more energized by brainstorming new ideas than by optimizing existing systems.',
    options: LIKERT_5 },
  { id: 'm4_csq_08', module: 4, quotient: 'CSQ', dimension: 'cognitive_respect', format: 'likert',
    text: 'I genuinely respect ways of thinking that are different from my own.',
    options: LIKERT_5 },
]

// ════════════════════════════════════════════
// MODULE 5: Your Depth Profile (Shadow) — 28 questions
// ACC (6) + EMP (5) + STB (5) + SAF (6) + DEP (6)
// ════════════════════════════════════════════
const MODULE_5: AssessmentQuestion[] = [
  // ── ACC: Accountability Index ──
  { id: 'm5_acc_01', module: 5, quotient: 'ACC', dimension: 'externalization', format: 'scenario',
    text: 'When a past partner told you that something you did hurt them, what was your most honest first reaction?',
    options: [
      { value: 5, label: 'I listened and tried to understand their perspective' },
      { value: 4, label: 'I felt bad and wanted to make it right' },
      { value: 3, label: 'I sometimes got defensive but eventually came around' },
      { value: 2, label: 'I usually felt they were being too sensitive' },
      { value: 1, label: 'I explained why they were wrong to feel that way' },
    ] },
  { id: 'm5_acc_02', module: 5, quotient: 'ACC', dimension: 'externalization', format: 'scenario',
    text: 'How often have past partners accused you of being selfish or dismissive?',
    options: [
      { value: 5, label: 'Never or almost never' },
      { value: 4, label: 'Once, and I took it to heart' },
      { value: 3, label: 'A few times — some of it was fair' },
      { value: 2, label: 'Multiple partners have said this' },
      { value: 1, label: 'Frequently, but I think they were projecting' },
    ] },
  { id: 'm5_acc_03', module: 5, quotient: 'ACC', dimension: 'emotional_labor', format: 'scenario',
    text: 'Think of your last three relationships. Who carried more emotional labor?',
    options: [
      { value: 5, label: 'We shared it roughly equally' },
      { value: 4, label: 'I carried more of it' },
      { value: 3, label: 'They carried more, and I was aware of it' },
      { value: 2, label: 'They carried more, but I didn\'t realize until after' },
      { value: 1, label: 'I\'m not sure what emotional labor means in this context' },
    ] },
  { id: 'm5_acc_04', module: 5, quotient: 'ACC', dimension: 'feedback_response', format: 'scenario',
    text: 'How do you typically respond when someone you respect gives you feedback you disagree with?',
    options: [
      { value: 5, label: 'I consider it seriously even if I ultimately disagree' },
      { value: 4, label: 'I try to see their point, though it\'s hard sometimes' },
      { value: 3, label: 'I listen politely but usually stick to my original view' },
      { value: 2, label: 'I explain why their feedback doesn\'t apply to me' },
      { value: 1, label: 'I feel frustrated — people don\'t understand my situation' },
    ] },
  { id: 'm5_acc_05', module: 5, quotient: 'ACC', dimension: 'entitlement', format: 'scenario',
    text: 'Have you ever ended a relationship primarily because you felt your partner simply didn\'t appreciate you enough?',
    options: [
      { value: 5, label: 'No — if appreciation was lacking, I communicated about it first' },
      { value: 4, label: 'Once, after extensive effort to resolve it' },
      { value: 3, label: 'Once or twice, when I felt consistently undervalued' },
      { value: 2, label: 'A few times — I seem to attract ungrateful partners' },
      { value: 1, label: 'Yes, multiple times — I deserve to be treated better' },
    ] },
  { id: 'm5_acc_06', module: 5, quotient: 'ACC', dimension: 'ownership', format: 'likert',
    text: 'When a relationship ends, I can clearly identify what I contributed to its failure.',
    options: LIKERT_5 },

  // ── EMP: Empathy History Index ──
  { id: 'm5_emp_01', module: 5, quotient: 'EMP', dimension: 'partner_pain', format: 'scenario',
    text: 'When a past partner was going through something painful, what did you typically do?',
    options: [
      { value: 5, label: 'I was fully present, asked what they needed, and followed through' },
      { value: 4, label: 'I tried to be supportive, though I didn\'t always know how' },
      { value: 3, label: 'I offered practical advice to help fix the situation' },
      { value: 2, label: 'I gave them space — I figured they\'d sort it out' },
      { value: 1, label: 'I found it draining and sometimes pulled away' },
    ] },
  { id: 'm5_emp_02', module: 5, quotient: 'EMP', dimension: 'intentional_harm', format: 'scenario',
    text: 'Have you ever done something in a relationship that you knew would hurt your partner — and did it anyway?',
    options: [
      { value: 5, label: 'No — I would never knowingly cause pain to someone I love' },
      { value: 4, label: 'Once, and I deeply regret it' },
      { value: 3, label: 'A few times, in moments of anger or frustration' },
      { value: 2, label: 'Yes — sometimes they needed to feel consequences' },
      { value: 1, label: 'Yes — but they usually brought it on themselves' },
    ] },
  { id: 'm5_emp_03', module: 5, quotient: 'EMP', dimension: 'promises', format: 'likert',
    text: 'The promises and agreements I make in a relationship are deeply important to me.',
    options: LIKERT_5 },
  { id: 'm5_emp_04', module: 5, quotient: 'EMP', dimension: 'coldness', format: 'scenario',
    text: 'Have past partners ever described you as cold, distant, or unable to truly connect emotionally?',
    options: [
      { value: 5, label: 'No, never' },
      { value: 4, label: 'Once, during a particularly difficult time' },
      { value: 3, label: 'Occasionally — I can be reserved sometimes' },
      { value: 2, label: 'Multiple partners have said this' },
      { value: 1, label: 'Yes, but I think they confused independence for coldness' },
    ] },
  { id: 'm5_emp_05', module: 5, quotient: 'EMP', dimension: 'guilt_duration', format: 'scenario',
    text: 'When you\'ve caused someone real harm in a relationship, how long did the guilt stay with you?',
    options: [
      { value: 5, label: 'It still bothers me to this day' },
      { value: 4, label: 'A long time — months or more' },
      { value: 3, label: 'Weeks, then I made peace with it' },
      { value: 2, label: 'Briefly — I moved on fairly quickly' },
      { value: 1, label: 'Honestly, I didn\'t feel much guilt' },
    ] },

  // ── STB: Emotional Stability Pattern ──
  { id: 'm5_stb_01', module: 5, quotient: 'STB', dimension: 'abandonment', format: 'scenario',
    text: 'How do you feel when a partner you\'re close to says they need some time to themselves?',
    options: [
      { value: 5, label: 'I understand — everyone needs personal space' },
      { value: 4, label: 'I\'m fine with it, though I might feel a little unsettled' },
      { value: 3, label: 'I try to be okay with it, but it triggers some anxiety' },
      { value: 2, label: 'I worry they\'re pulling away from me' },
      { value: 1, label: 'I feel panicked or rejected, even if I know it\'s irrational' },
    ] },
  { id: 'm5_stb_02', module: 5, quotient: 'STB', dimension: 'splitting', format: 'scenario',
    text: 'Have you ever gone from feeling like a partner was perfect to suddenly feeling like they were the worst person for you?',
    options: [
      { value: 5, label: 'No — my view of partners stays fairly consistent' },
      { value: 4, label: 'My feelings shift, but not that dramatically' },
      { value: 3, label: 'Occasionally, during intense emotional moments' },
      { value: 2, label: 'Yes, this has happened in a couple of relationships' },
      { value: 1, label: 'Yes, this is a pattern across most of my relationships' },
    ] },
  { id: 'm5_stb_03', module: 5, quotient: 'STB', dimension: 'emotional_range', format: 'scenario',
    text: 'In your most intense relationship, how would you describe your emotional range during conflicts?',
    options: [
      { value: 5, label: 'Manageable — I stayed within a reasonable emotional range' },
      { value: 4, label: 'Sometimes intense, but I could bring myself back' },
      { value: 3, label: 'Very intense — I felt emotions at maximum volume' },
      { value: 2, label: 'Overwhelming — I sometimes couldn\'t control my reactions' },
      { value: 1, label: 'Explosive — I said or did things I deeply regret' },
    ] },
  { id: 'm5_stb_04', module: 5, quotient: 'STB', dimension: 'impulsivity', format: 'scenario',
    text: 'Have you ever done something impulsive during a relationship low-point to cope with emotional pain?',
    options: [
      { value: 5, label: 'No — I have healthy ways of managing difficult emotions' },
      { value: 4, label: 'Once or twice, minor things I course-corrected quickly' },
      { value: 3, label: 'A few times — spending, drinking, or risky decisions' },
      { value: 2, label: 'Yes — impulsive coping is a pattern I recognize in myself' },
      { value: 1, label: 'Yes — I\'ve done things that caused real damage to cope' },
    ] },
  { id: 'm5_stb_05', module: 5, quotient: 'STB', dimension: 'identity', format: 'scenario',
    text: 'How clear is your sense of who you are outside of your romantic relationships?',
    options: [
      { value: 5, label: 'Very clear — I have a strong sense of self regardless' },
      { value: 4, label: 'Mostly clear, though relationships enhance my identity' },
      { value: 3, label: 'Somewhat clear — I sometimes lose myself in relationships' },
      { value: 2, label: 'Unclear — my identity shifts significantly based on who I\'m with' },
      { value: 1, label: 'I\'m not sure who I am without a partner' },
    ] },

  // ── SAF: Relational Safety Score ──
  { id: 'm5_saf_01', module: 5, quotient: 'SAF', dimension: 'monitoring', format: 'scenario',
    text: 'Have you ever monitored a partner\'s phone, location, or communications without their knowledge or consent?',
    options: [
      { value: 5, label: 'No, never — I respect privacy completely' },
      { value: 4, label: 'I\'ve been tempted but didn\'t act on it' },
      { value: 3, label: 'Once, during a specific crisis of trust' },
      { value: 2, label: 'A few times — I needed to know the truth' },
      { value: 1, label: 'Yes, regularly — trust but verify' },
    ] },
  { id: 'm5_saf_02', module: 5, quotient: 'SAF', dimension: 'anger_expression', format: 'scenario',
    text: 'When you\'ve been very angry at a partner, what has that looked like at its worst?',
    options: [
      { value: 5, label: 'I expressed frustration clearly but never raised my voice' },
      { value: 4, label: 'I raised my voice but never said anything cruel' },
      { value: 3, label: 'I\'ve said things designed to hurt in the moment' },
      { value: 2, label: 'I\'ve thrown things, punched walls, or broken objects' },
      { value: 1, label: 'I\'ve physically intimidated or blocked a partner\'s exit' },
    ] },
  { id: 'm5_saf_03', module: 5, quotient: 'SAF', dimension: 'control_perception', format: 'scenario',
    text: 'Have past partners ever described you as controlling or intimidating when you\'re upset?',
    options: [
      { value: 5, label: 'No, never' },
      { value: 4, label: 'Once, and I took it very seriously' },
      { value: 3, label: 'Occasionally, though I think they were overreacting' },
      { value: 2, label: 'Multiple partners have said this' },
      { value: 1, label: 'Yes, but I was just being passionate or protective' },
    ] },
  { id: 'm5_saf_04', module: 5, quotient: 'SAF', dimension: 'financial_control', format: 'scenario',
    text: 'Have you ever used financial control — withholding money or resources — as a tool in a conflict?',
    options: [
      { value: 5, label: 'No, never — finances are separate from relationship dynamics' },
      { value: 4, label: 'No, though we\'ve disagreed about money' },
      { value: 3, label: 'I\'ve mentioned financial contributions during arguments' },
      { value: 2, label: 'I\'ve restricted spending as a consequence during conflicts' },
      { value: 1, label: 'Yes — controlling resources is sometimes necessary' },
    ] },
  { id: 'm5_saf_05', module: 5, quotient: 'SAF', dimension: 'self_harm_threat', format: 'scenario',
    text: 'Have you ever threatened to hurt yourself to influence what a partner decided to do?',
    options: [
      { value: 5, label: 'No, never' },
      { value: 4, label: 'I\'ve expressed genuine distress, but never as manipulation' },
      { value: 3, label: 'Once, during an extremely desperate moment' },
      { value: 2, label: 'A few times, when I felt I had no other options' },
      { value: 1, label: 'Yes — they needed to understand the impact of their decisions' },
    ] },
  { id: 'm5_saf_06', module: 5, quotient: 'SAF', dimension: 'isolation', format: 'frequency',
    text: 'How often did you try to limit a partner\'s time with their friends or family?',
    options: [
      { value: 5, label: 'Never — their relationships are their own' },
      { value: 4, label: 'Rarely — only when specific people were genuinely harmful' },
      { value: 3, label: 'Sometimes — I preferred us to spend time together' },
      { value: 2, label: 'Often — I felt like an afterthought otherwise' },
      { value: 1, label: 'Frequently — our relationship should come first' },
    ] },

  // ── DEP: Dependency & Coping Index ──
  { id: 'm5_dep_01', module: 5, quotient: 'DEP', dimension: 'coping_method', format: 'scenario',
    text: 'During difficult relationship periods, how did you most commonly manage emotional pain?',
    options: [
      { value: 5, label: 'Healthy outlets — exercise, journaling, therapy, friends' },
      { value: 4, label: 'Mostly healthy, with occasional comfort eating or extra screen time' },
      { value: 3, label: 'A mix — some healthy coping, some drinking or avoidance' },
      { value: 2, label: 'Primarily through alcohol, substances, shopping, or other escapes' },
      { value: 1, label: 'I relied heavily on a substance or compulsive behavior to get through' },
    ] },
  { id: 'm5_dep_02', module: 5, quotient: 'DEP', dimension: 'partner_concern', format: 'scenario',
    text: 'Have past partners ever expressed concern about your use of alcohol, substances, or any compulsive behavior?',
    options: [
      { value: 5, label: 'No, never' },
      { value: 4, label: 'Once, during a temporary rough patch' },
      { value: 3, label: 'Occasionally — there may have been some truth to it' },
      { value: 2, label: 'Multiple partners have raised this concern' },
      { value: 1, label: 'Yes, but they were overreacting' },
    ] },
  { id: 'm5_dep_03', module: 5, quotient: 'DEP', dimension: 'cutback_success', format: 'scenario',
    text: 'When you\'ve tried to cut back on a habit that affects your relationships, how successful were you?',
    options: [
      { value: 5, label: 'I don\'t have habits that negatively affect relationships' },
      { value: 4, label: 'I successfully cut back when I decided to' },
      { value: 3, label: 'I cut back temporarily but eventually returned to old patterns' },
      { value: 2, label: 'I struggled significantly to change despite wanting to' },
      { value: 1, label: 'I haven\'t been able to change despite multiple attempts' },
    ] },
  { id: 'm5_dep_04', module: 5, quotient: 'DEP', dimension: 'missed_moments', format: 'scenario',
    text: 'Have you ever missed important moments in a relationship because of a personal habit or behavior?',
    options: [
      { value: 5, label: 'No — I prioritize what matters' },
      { value: 4, label: 'Once, and I learned from it' },
      { value: 3, label: 'A few times — it\'s something I\'m working on' },
      { value: 2, label: 'More times than I\'d like to admit' },
      { value: 1, label: 'Yes, and it contributed to relationship endings' },
    ] },
  { id: 'm5_dep_05', module: 5, quotient: 'DEP', dimension: 'codependency', format: 'likert',
    text: 'My emotional stability in past relationships depended heavily on my partner\'s mood or approval.',
    options: LIKERT_5, reverseScored: true },
  { id: 'm5_dep_06', module: 5, quotient: 'DEP', dimension: 'codependency', format: 'likert',
    text: 'I tend to lose myself in caring for a partner, neglecting my own needs in the process.',
    options: LIKERT_5, reverseScored: true },
]

// ════════════════════════════════════════════
// MODULE 6: Money & Life — 22 questions
// FMI (4) + FSB (4) + FPL (4) + FIQ (3) + FCM (4) + CDF (3)
// ════════════════════════════════════════════
const MODULE_6: AssessmentQuestion[] = [
  // ── FMI: Financial Mindset Index ──
  { id: 'm6_fmi_01', module: 6, quotient: 'FMI', dimension: 'money_avoidance', format: 'likert',
    text: 'Thinking about money makes me anxious, so I tend to avoid it.',
    options: LIKERT_5, reverseScored: true },
  { id: 'm6_fmi_02', module: 6, quotient: 'FMI', dimension: 'money_worship', format: 'likert',
    text: 'If I had significantly more money, most of my problems would be solved.',
    options: LIKERT_5, reverseScored: true },
  { id: 'm6_fmi_03', module: 6, quotient: 'FMI', dimension: 'money_status', format: 'likert',
    text: 'How much money a person has says a lot about their worth as a person.',
    options: LIKERT_5, reverseScored: true },
  { id: 'm6_fmi_04', module: 6, quotient: 'FMI', dimension: 'self_efficacy', format: 'likert',
    text: 'I am confident in my ability to manage money wisely.',
    options: LIKERT_5 },

  // ── FSB: Spending Behavior Profile ──
  { id: 'm6_fsb_01', module: 6, quotient: 'FSB', dimension: 'impulsive', format: 'frequency',
    text: 'I make purchases on impulse that I later wish I hadn\'t.',
    options: FREQUENCY_5, reverseScored: true },
  { id: 'm6_fsb_02', module: 6, quotient: 'FSB', dimension: 'deliberate', format: 'likert',
    text: 'Before a significant purchase, I research thoroughly and compare options.',
    options: LIKERT_5 },
  { id: 'm6_fsb_03', module: 6, quotient: 'FSB', dimension: 'emotional_spending', format: 'frequency',
    text: 'I use shopping or spending as a way to cope with stress or negative emotions.',
    options: FREQUENCY_5, reverseScored: true },
  { id: 'm6_fsb_04', module: 6, quotient: 'FSB', dimension: 'lifestyle_inflation', format: 'likert',
    text: 'When my income increases, my spending increases by about the same amount.',
    options: LIKERT_5, reverseScored: true },

  // ── FPL: Financial Planning Quotient ──
  { id: 'm6_fpl_01', module: 6, quotient: 'FPL', dimension: 'budgeting', format: 'scenario',
    text: 'How do you currently track your spending?',
    options: [
      { value: 5, label: 'Detailed budget that I review weekly or monthly' },
      { value: 4, label: 'I use an app or system to monitor spending' },
      { value: 3, label: 'I have a rough idea but don\'t track closely' },
      { value: 2, label: 'I check my bank account occasionally' },
      { value: 1, label: 'I don\'t track my spending at all' },
    ] },
  { id: 'm6_fpl_02', module: 6, quotient: 'FPL', dimension: 'emergency', format: 'scenario',
    text: 'If you lost your income tomorrow, how long could you sustain your current lifestyle?',
    options: [
      { value: 5, label: '6+ months comfortably' },
      { value: 4, label: '3-6 months with adjustments' },
      { value: 3, label: '1-3 months' },
      { value: 2, label: 'Less than a month' },
      { value: 1, label: 'I would be in immediate financial distress' },
    ] },
  { id: 'm6_fpl_03', module: 6, quotient: 'FPL', dimension: 'retirement', format: 'likert',
    text: 'I am actively contributing to retirement savings or long-term investments.',
    options: LIKERT_5 },
  { id: 'm6_fpl_04', module: 6, quotient: 'FPL', dimension: 'goal_setting', format: 'likert',
    text: 'I have specific financial goals with target dates and concrete plans to reach them.',
    options: LIKERT_5 },

  // ── FIQ: Investment Intelligence Quotient ──
  { id: 'm6_fiq_01', module: 6, quotient: 'FIQ', dimension: 'risk_tolerance', format: 'scenario',
    text: 'When it comes to financial risk, which best describes you?',
    options: [
      { value: 1, label: 'I avoid all risk — safety first' },
      { value: 2, label: 'I prefer low-risk, stable investments' },
      { value: 3, label: 'I balance some risk with stability' },
      { value: 4, label: 'I\'m comfortable with significant risk for potential gain' },
      { value: 5, label: 'I actively seek high-risk, high-reward opportunities' },
    ] },
  { id: 'm6_fiq_02', module: 6, quotient: 'FIQ', dimension: 'bias_awareness', format: 'likert',
    text: 'I am aware of psychological biases (like loss aversion) that can affect financial decisions.',
    options: LIKERT_5 },
  { id: 'm6_fiq_03', module: 6, quotient: 'FIQ', dimension: 'wealth_philosophy', format: 'scenario',
    text: 'My primary financial philosophy is:',
    options: [
      { value: 1, label: 'Money is for enjoying life now' },
      { value: 2, label: 'A balance of enjoying now and saving for later' },
      { value: 3, label: 'Building wealth steadily over time' },
      { value: 4, label: 'Maximizing wealth accumulation as a primary goal' },
      { value: 5, label: 'Building generational wealth and legacy' },
    ] },

  // ── FCM: Financial Communication Score ──
  { id: 'm6_fcm_01', module: 6, quotient: 'FCM', dimension: 'transparency', format: 'likert',
    text: 'I am completely open about my income, debts, and spending with a partner.',
    options: LIKERT_5 },
  { id: 'm6_fcm_02', module: 6, quotient: 'FCM', dimension: 'conflict_style', format: 'scenario',
    text: 'When you and a partner disagree about a financial decision, you typically:',
    options: [
      { value: 5, label: 'Discuss it calmly until we find a solution we both accept' },
      { value: 4, label: 'Talk it through, even if it gets a bit tense' },
      { value: 3, label: 'Compromise quickly to avoid the tension' },
      { value: 2, label: 'Avoid the conversation — money talks are stressful' },
      { value: 1, label: 'Get frustrated — I usually know what\'s best financially' },
    ] },
  { id: 'm6_fcm_03', module: 6, quotient: 'FCM', dimension: 'vulnerability', format: 'likert',
    text: 'I am comfortable sharing financial fears, mistakes, and shame with a partner.',
    options: LIKERT_5 },
  { id: 'm6_fcm_04', module: 6, quotient: 'FCM', dimension: 'concealment', format: 'scenario',
    text: 'Have you ever hidden a purchase, debt, or financial decision from a partner?',
    options: [
      { value: 5, label: 'No, never' },
      { value: 4, label: 'A small purchase once — nothing significant' },
      { value: 3, label: 'Occasionally — minor things I didn\'t think mattered' },
      { value: 2, label: 'Yes — I\'ve hidden significant financial information' },
      { value: 1, label: 'Yes — I maintain financial privacy as a personal boundary' },
    ] },

  // ── CDF: Credit & Debt Framework ──
  { id: 'm6_cdf_01', module: 6, quotient: 'CDF', dimension: 'debt_awareness', format: 'scenario',
    text: 'How accurately do you know your current total debt?',
    options: [
      { value: 5, label: 'I know the exact amount, interest rates, and payoff dates' },
      { value: 4, label: 'I have a good general idea' },
      { value: 3, label: 'I know roughly, but haven\'t checked recently' },
      { value: 2, label: 'I\'m not sure of the exact numbers' },
      { value: 1, label: 'I avoid looking at my debt' },
    ] },
  { id: 'm6_cdf_02', module: 6, quotient: 'CDF', dimension: 'reduction', format: 'scenario',
    text: 'My approach to existing debt is:',
    options: [
      { value: 5, label: 'I have no debt, or I\'m actively paying it down with a plan' },
      { value: 4, label: 'I make more than minimum payments regularly' },
      { value: 3, label: 'I make minimum payments consistently' },
      { value: 2, label: 'I sometimes miss payments or pay inconsistently' },
      { value: 1, label: 'I\'m accumulating more debt than I\'m paying off' },
    ] },
  { id: 'm6_cdf_03', module: 6, quotient: 'CDF', dimension: 'stress_response', format: 'scenario',
    text: 'When you think about your financial obligations, your dominant feeling is:',
    options: [
      { value: 5, label: 'Confident — I have a handle on it' },
      { value: 4, label: 'Mostly comfortable, with occasional stress' },
      { value: 3, label: 'Manageable anxiety that I can work through' },
      { value: 2, label: 'Significant stress that affects other areas of life' },
      { value: 1, label: 'Overwhelming — I try not to think about it' },
    ] },
]

// ═══ Export organized by module ═══
export const QUESTION_BANK: Record<number, AssessmentQuestion[]> = {
  1: MODULE_1,
  2: MODULE_2,
  3: MODULE_3,
  4: MODULE_4,
  5: MODULE_5,
  6: MODULE_6,
}

export function getModuleQuestions(module: number): AssessmentQuestion[] {
  return QUESTION_BANK[module] ?? []
}

export function getTotalQuestionCount(): number {
  return Object.values(QUESTION_BANK).reduce((sum, qs) => sum + qs.length, 0)
}
